config/routes.rb
Top5::Application.routes.draw do

  root :to => "toplists#index"
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/twitter', :as => 'signin'
  match 'signout', :to => 'sessions#destroy', :as => 'signout'
  
  match 'about', :to => 'statics#about', :as => 'about'
  
  resources :categories do
    resources :toplists
  end
  resources :topics do
    resources :toplists
  end
  resources :users do
    resources :toplists
  end
  resources :toplists
  

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end
  
  def self.create_from_hash(hash, user=nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create( :user => user,
                          :uid => hash['uid'],
                          :provider => hash['provider'],
                          :ctoken => hash['credentials']['token'],
                          :csecret => hash['credentials']['secret'])
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics
  has_many :toplists, :through => :topics
  
  validates_presence_of :title
  
  named_scope :ordered, :order => :position
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :toplist
  
  validates_presence_of :title
  validates_presence_of :position
  
  default_scope :order => :position
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :category
  has_many :toplists, :dependent => :destroy
  
  named_scope :ordered_by_activity, :order => 'toplists_count DESC'
end

app/models/toplist.rb
class Toplist < ActiveRecord::Base
  belongs_to :user, :counter_cache => true
  belongs_to :topic, :counter_cache => true
  has_many :items, :dependent => :destroy
  
  validates :user_id, :presence => true
  validates :topic_id, :presence => true
  validates_uniqueness_of :topic_id, :scope => :user_id
  
  accepts_nested_attributes_for :topic, :reject_if => proc { |attributes| attributes['title'].blank? }
  accepts_nested_attributes_for :items
  
  named_scope :ordered, :order => 'updated_at desc'
  
  def validate
    errors[:base] << 'Please use every item just once' if items.collect(&:title).uniq.size < 5
  end
  
  def build_items
    5.times do |i|
      items.build(:position => i + 1)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :toplists, :dependent => :destroy
  
  named_scope :ordered_by_activity, :order => 'toplists_count DESC'
  
  def self.create_from_hash!(hash)
    create(:name => hash['user_info']['name'], :image => hash['user_info']['image'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  
  def signed_in?
    !!current_user # == current_user?
  end
  
  helper_method :current_user, :signed_in?
  
  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
  
  def require_user
    session[:return_to] = request.url
    redirect_to '/auth/twitter' unless signed_in?
  end
  
  def redirect_back_or_default(default)
    return_to = session[:return_to]
    session[:return_to] = nil
    if return_to
      redirect_to(return_to)
    else
      redirect_to(default)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['rack.auth']
    unless @auth = Authorization.find_from_hash(auth)
      @auth = Authorization.create_from_hash(auth, current_user)
    end
    self.current_user = @auth.user
    
    notice = "Welcome, #{current_user.name}."
    redirect_back_or_default root_path
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def about; end
end

app/controllers/toplists_controller.rb
class ToplistsController < ApplicationController
  before_filter :require_user, :only => [:new, :create]
  before_filter :find_parent
  
  def index
    @toplists = @parent ? @parent.toplists : Toplist.ordered
    @toplists.limit(10)
  end
  
  def new
    @toplist = Toplist.new
    @toplist.build_items
  end
  
  def create
    @toplist = Toplist.new(params[:toplist])
    @toplist.user = current_user
    
    if @toplist.save
      redirect_to toplists_path
      #redirect_to user_toplists_path(current_user)
    else
      render :new
    end
  end
  
protected

  def find_parent
    @parent = Category.find(params[:category_id]) if params[:category_id]
    @parent = Topic.find(params[:topic_id]) if params[:topic_id]
    @parent  = User.find(params[:user_id]) if params[:user_id]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_item.html.erb
<li><%= item.title %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Interchange  
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20100704

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Top5</title>
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
</head>
<body>
<div id="wrapper">
	<div id="header">
		<div id="logo">
			<h1><%= link_to root_path do %>favorite-five<% end %></h1>
			<p>Share your Taste.</p>
		</div>
		<div id="search">
			<form method="get" action="">
				<fieldset>
					<input type="text" name="s" id="search-text" size="15" value="enter keywords here..." />
					<input type="submit" id="search-submit" value="GO" />
				</fieldset>
			</form>
		</div>
	</div>
	<!-- end #header -->
	<div id="menu">
		<ul>
			<li class="current_page_item"><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'Add New List', new_toplist_path %></li>
			<%#
			<li><a href="#">My Lists</a></li>
			<li><a href="#">Propose New Topic</a></li>
			<li><a href="#">Contact</a></li>
			%>
			<% unless signed_in? %>
			  <li class="last"><%= link_to 'Sign in with your Twitter account', signin_path %></li>
			<% else %>
			  <li class="last">
			    <%= link_to signout_path do %>
			      <%= image_tag current_user.image, :size => '32x32' %> <span><%= current_user.name %></span>
			    <% end%>
			  </li>
			<% end %>
		</ul>
	</div>
	<!-- end #menu -->
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
				  <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
				  <%= yield %>
					<div style="clear: both;">&nbsp;</div>
				</div>
				<!-- end #content -->
				<div id="sidebar">
					<ul>
						<li>
							<h2>Categories</h2>
							<ul>
							  <li><%= link_to 'All', toplists_path %></li>
							  <% Category.ordered.limit(5).each do |category| %>
							    <li><%= link_to category.title, category_toplists_path(category) %></li>
							  <% end %>
							</ul>
						</li>
						<li>
							<h2>TOP5 Topics</h2>
							<ul>
							  <li><%= link_to 'All', toplists_path %></li>
							  <% Topic.ordered_by_activity.limit(5).each do |topic| %>
							    <li><%= link_to topic.title, topic_toplists_path(topic) %></li>
							  <% end %>
							</ul>
						</li>
						<li>
							<h2>TOP Users</h2>
							<ul>
							  <li><%= link_to 'All', toplists_path %></li>
							  <% User.ordered_by_activity.limit(5).each do |user| %>
							    <li><%= link_to user_toplists_path(user) do %><%= image_tag user.image, :size => '16x16' %> <%= user.name %><% end %></li>
							  <% end %>
							</ul>
						</li>
					</ul>
				</div>
				<!-- end #sidebar -->
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page -->
</div>
<div id="footer">
	<p>
	  <%= link_to 'about me', about_path %> | 
	  Design by <a href="http://www.freecsstemplates.org/" target="_blank" > CSS Templates</a>.
	</p>
</div>
<!-- end #footer -->
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
<div id="errorExplanation">  
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>  
  <ul>  
  <% target.errors.full_messages.each do |msg| %>  
    <li><%= msg %></li>  
  <% end %>  
  </ul>  
</div>  
<% end %>

app/views/statics/about.html.erb
<h2 class="title">About Me</h2>

<p><%= link_to 'Oliver Schemmel', 'http://twitter.com/oliver_schemmel', :target => 'blank' %> is a Rails Programmer for <%= link_to 'Katzer + Neumann GmbH', 'http://www.katzer-neumann.de', :target => 'blank' %> .</p>
<p>Inspired by the Book/Movie 'High Fidelity' by Nick Hornby and after thousands of TOP5 - Lists on paper he decided to write a Web-Application in order to organize his various TOP5-Lists.</p>
<p>He looks forward to many fellow users to share thoughts and taste.</p>

app/views/toplists/_toplist.html.erb
<div class="toplist">
	<h2 class="title"><a href="#"><%= toplist.topic.title %></a></h2>
	<p class="meta">Created by <%= link_to user_toplists_path(toplist.user) do %><%= image_tag toplist.user.image, :size => '16x16' %><%= toplist.user.name %><% end %> on <%= toplist.updated_at.to_s(:short) %>
		&nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <%= link_to 'Add Your Own', new_toplist_path %>
	<ol class="items">
    <%= render :partial => toplist.items %>
	</ol>
</div>

app/views/toplists/index.html.erb
<%= render :partial => @toplists %>

app/views/toplists/new.html.erb
<% form_for @toplist do |f| %>
  <%= render 'shared/error_messages', :target => @toplist %>
  <fieldset>
    <legend>New Toplist</legend>
    <ol>
      <li>
        <%= f.select :topic_id, Topic.all.collect {|topic| [topic.title, topic.id]} %>
      </li>
      <% f.fields_for :items do |g| %>
        <%= g.hidden_field :position %>
        <li>
          <%= g.label :title, g.object.position %> <%= g.text_field :title %>
        </li>
      <% end %>
    </ol>
  </fieldset>
  <fieldset class="submit">
    <%= f.submit %>
  </fieldset>
<% end %>